M5_SitioMedico-01_JuanArancibia/M5_SitioMedico/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
    path('', include('app_forms.urls')),
    path('', include ('app2.urls')),
]

M5_SitioMedico-01_JuanArancibia/app1/urls.py
from django.urls import path
from . import views


app_name='app1'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('registro/', views.registro, name='registro'),
    path('login/', views.login, name='login'),
    path('fichaPaciente/', views.fichaPaciente, name='fichaPaciente'),
    
    path('calendario/', views.calendarioHoras, name='calendario'),
    path('administracion/', views.administracion, name='administracion'),
    
]

M5_SitioMedico-01_JuanArancibia/app_forms/urls.py
from django.urls import path
from . import views


app_name='app_forms'

urlpatterns = [
    path('crear_pacientes/', views.crear_pacientes, name='crear_pacientes'),
    path('lista_pacientes/', views.lista_pacientes, name='lista_pacientes'),
    path('<rut>/eliminar_pacientes', views.eliminar_pacientes, name='eliminar_pacientes'),
    path('pacientes_creados/', views.pacientes_creados, name='pacientes_creados'),
    path('ingresar_examenes/', views.ingresar_examenes, name='ingresar_examenes'),
]

M5_SitioMedico-01_JuanArancibia/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'app1/css/estilos.css' %}">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar navbar-dark bg-primary">
        <a class="navbar-brand" href="{% url 'app1:inicio' %}">InterSalud</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
            aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    

        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" >Administración </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app1:login' %}">Iniciar Sesion</a>
                </li>
                
                <!--Se agregan nuevas páginas a la barra de navegación-->
                
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app_forms:crear_pacientes' %}">Crear paciente</a>
                </li>
               
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app_forms:pacientes_creados' %}">Lista Pacientes</a>
                </li> 
                <!--En la lista_pacientes esta la opcion de de eliminarar paciente para eliminar-->
                
            </ul>

        </div>
    </nav>


    {% block contenidos %}{% endblock %}

    <!-- Enlaces -->
    <div class="container">
        <p>Enlaces de interés:</p>
        <a href="http://www.ist.cl/centros-de-salud/hospital-clinico-ist-vina-del-mar/" type="button"
            class="btn btn-info btn-block">Hospital Clínico</a>
        <a href="https://www.parquedelmar.cl/" type="button" class="btn btn-info btn-block">Cementerio Parque del
            Mar</a>
        <a href="https://samu.cl/" type="button" class="btn btn-info btn-block">SAMU</a>
        <a href="https://www.fonasa.cl/sites/fonasa/inicio" type="button" class="btn btn-info btn-block">FONASA</a>
        <a href="http://www.supersalud.gob.cl/664/w3-article-2528.html" type="button"
            class="btn btn-info btn-block">Superintendencia de Isapres</a>
    </div>


    <!-- Social media RRSS-->
    <div class="social">
        <header><img src="{% static 'app1/img/logo.png' %}" width="15%" alt=""></header>

        <p class="social-media-title"><i class="icon icon-socialmedia-title"></i> Conversemos en:</p>
        <a href="https://www.facebook.com/ciudaddelmar"><img src="{% static 'app1/img/facebook.png'%}" width=5%
                alt="facebook"></a>
        <a href="https://www.youtube.com/user/clinicaciudaddelmar"><img src="{% static 'app1/img/youtube.png' %}"
                width=5% alt="youtube"></a>
        <a href="https://www.linkedin.com/company/cl-nica-ciudad-del-mar"><img
                src="{% static 'app1/img/linkedin.png' %}" width=4% alt="linkedin"></a>
        <a href="https://www.instagram.com/ciudaddelmar"><img src="{% static 'app1/img/instagram.png' %}" width=4%
                alt="instagram"></a>
    </div>

    <!-- jQuery, Popper.js, Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
        </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
        </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous">
        </script>


    <footer>
        <h6>Intersalud | 13 Norte 635, Viña del Mar | (032) 245 10 00 | info@ccdm.cl | </h6>
        2021 &copy; Intersalud | Tu salud en buenas manos.
    </footer>
</body>

</html>