M5_SitioMedico-01_JuanArancibia/M5_SitioMedico/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
    path('', include('app_forms.urls')),
    path('', include ('app2.urls')),
]

M5_SitioMedico-01_JuanArancibia/app1/urls.py
from django.urls import path
from . import views


app_name='app1'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('registro/', views.registro, name='registro'),
    path('login/', views.login, name='login'),
    path('fichaPaciente/', views.fichaPaciente, name='fichaPaciente'),
    
    path('calendario/', views.calendarioHoras, name='calendario'),
    path('administracion/', views.administracion, name='administracion'),
    
]

M5_SitioMedico-01_JuanArancibia/app_forms/urls.py
from django.urls import path
from . import views


app_name='app_forms'

urlpatterns = [
    path('crear_pacientes/', views.crear_pacientes, name='crear_pacientes'),
    path('lista_pacientes/', views.lista_pacientes, name='lista_pacientes'),
    path('<rut>/eliminar_pacientes', views.eliminar_pacientes, name='eliminar_pacientes'),
    path('pacientes_creados/', views.pacientes_creados, name='pacientes_creados'),
    path('ingresar_examenes/', views.ingresar_examenes, name='ingresar_examenes'),
]

M5_SitioMedico-01_JuanArancibia/app_forms/models.py
from django.db import models

# Create your models here.

M5_SitioMedico-01_JuanArancibia/app_forms/forms.py
from django import forms
from django.core import validators


class FormularioPacientes(forms.Form):
    rut = forms.CharField()
    nombre = forms.CharField()
    apellido = forms.CharField()
    email = forms.CharField()
    tutor = forms.CharField()
    direccion = forms.CharField()
    enfermedades = forms.CharField()

class tipos_examenes(forms.Form):
    rut = forms.CharField()
    orina = forms.IntegerField()
    glucosa = forms.IntegerField()
    colesterol = forms.IntegerField()
    triglicerido = forms.IntegerField()
    bilirrubina = forms.IntegerField()
    fecha = forms.DateField()

M5_SitioMedico-01_JuanArancibia/app_forms/views.py
import json


from django.shortcuts import render, redirect
from .forms import FormularioPacientes, tipos_examenes

from django.conf import settings


def crear_pacientes(request):
        if request.method=="GET":
            formulario = FormularioPacientes()
            contex = {'formulario':formulario}
            return render(request, 'app_forms/crear_pacientes.html', contex)

        elif request.method=="POST":
            #print ("llego POST OK", request.POST)
            
            formulario_devuelto = FormularioPacientes(request.POST)
            
        if formulario_devuelto.is_valid() == True:
            datos_formulario = formulario_devuelto.cleaned_data
            filename = "/app_forms/data/pacientes.json"
            with open (str(settings.BASE_DIR)+filename, 'r') as file:  
                pacientes=json.load(file)
                pacientes['pacientes'].append(datos_formulario)
            with open (str(settings.BASE_DIR)+filename, 'w') as file:
                json.dump(pacientes, file)
            return redirect('app_forms:pacientes_creados')
        else:
            contex = {'formulario':formulario_devuelto}
            return render (request, 'app_forms/crear_pacientes.html', contex )



def lista_pacientes(request):
    filename = "/app_forms/data/pacientes.json"
    with open (str(settings.BASE_DIR)+filename, 'r') as file:
                pacientes=json.load(file)
    contex = {'lista_pacientes': pacientes['pacientes']} 
    return render(request, 'app_forms/lista_pacientes.html', contex)   

def eliminar_pacientes(request, rut):

    if request.method == "GET":
        context = {'rut': rut}
        return render(request, "app_forms/eliminar_pacientes.html", context)

    if request.method == "POST":
        filename= "/app_forms/data/pacientes.json"
        with open(str(settings.BASE_DIR)+filename, 'r') as file:
            data=json.load(file)
        for paciente in data['pacientes']:
            if str(paciente['rut'])==str(rut):
                data['pacientes'].remove(paciente)
                break
        with open(str(settings.BASE_DIR)+filename, 'w') as file:
            json.dump(data, file)
        
        return redirect('app_forms:pacientes_creados')

def pacientes_creados(request):
    filename = "/app_forms/data/pacientes.json"
    with open (str(settings.BASE_DIR)+filename, 'r') as file:
                pacientes=json.load(file)
    contex = {'lista_pacientes': pacientes['pacientes']}
    return render(request, 'app_forms/pacientes_creados.html',contex)

def ingresar_examenes(request):
    if request.method == "GET":
        examenes = tipos_examenes()
        context = {'examenes': examenes}
        return render(request, 'app_forms/Ingresar_examenes.html', context)

    elif(request.method == "POST"):
        #print("EL POST CONTIENE: ", request.POST)
        data2 = {}
        examenes_post = tipos_examenes(request.POST) 
        #print(type(examenes_post))
        if examenes_post.is_valid() == True:
            data = examenes_post.cleaned_data
            #print(data)
            data['fecha']=data['fecha'].strftime("%Y-%m-%d")
            #print("EL POST CONTIENE: ", data)
            data2['rut'] = {data['rut']: {'orina': data['orina'],'glucosa': data['glucosa'], 
            'colesterol': data['colesterol'], 'triglicerido': data['triglicerido'], 
            'bilirrubina': data['bilirrubina'],'fecha': data['fecha']}}
            #print(data2)
            archivo = "/app2/data/examenes.json" 
            with open(str(settings.BASE_DIR)+archivo,'r') as file:
                examenes = json.load(file)
                examenes['examenes'].append(data2)
            with open(str(settings.BASE_DIR)+archivo,'w') as file:
                json.dump(examenes, file)
            return redirect('app2:fichaMedica')
        else:
            context = {'examenes': examenes_post}
            return render(request, 'app_forms/Ingresar_examenes.html', context)         

M5_SitioMedico-01_JuanArancibia/app_forms/templates/app_forms/Ingresar_examenes.html
{% extends "base.html" %}

{% load static %}

{% block contenidos %}
<h1>Ingresar examenes</h1>
<div class = 'jumbotron'>
    <div class = 'center-text'>
        <form action="" method="POST"> 
            {% csrf_token %}
            <table>
                {{examenes.as_table}}
            </table>
            <input type="submit" value="Submit" onclick="verificado()">
            
        </form>
    </div>
</div>

<script>
    function verificado() {
    alert("El usuario ha sido registrado satisfactoriamente");
    }
</script>

{% endblock %}

M5_SitioMedico-01_JuanArancibia/app_forms/templates/app_forms/crear_pacientes.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'app1/css/estilos.css' %}">
</head>

<body>
    <!--Barra Navegacion-->
    <nav class="navbar navbar-expand-lg navbar navbar-dark bg-primary">
        <a class="navbar-brand" href="{% url 'app1:inicio' %}">InterSalud</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
            aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>


        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" >Administración </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app1:login' %}">Iniciar Sesion</a>
                </li>
                
                <!--Se agregan nuevas páginas a la barra de navegación-->
                
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app_forms:crear_pacientes' %}">Crear paciente</a>
                </li>
               
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app_forms:pacientes_creados' %}">Lista Pacientes</a>
                </li> 
                <!--En la lista_pacientes esta la opcion de de eliminarar paciente para eliminar-->
                                            
 
            </ul>

        </div>
    </nav>
<!--Fin Barra Navegación-->

    

    <div class="jumbotron">
        <div class="center-text">
            <form action="" method="POST" novalidate>
                {% csrf_token %}
                <table>
                    {{formulario.as_table}}
                </table>
                <input type="hidden" name="elemento" value="pacientes">
                <input type="submit" value="Crear">
            </form>

            <!--Se ingresan los datos de los pacientes-->
            
            {% for pacientes in lista_pacientes %}
                <div class="col-md-6 col-lg-3">
                <div class="card">
                    <div class="card-body">
                            <p class="card-text">{{pacientes.rut}}</p>
                            <p class="card-text">{{pacientes.nombre}}</p>
                            <p class="card-text">{{pacientes.apellido}}</p>
                            <p class="card-text">{{pacientes.email}}</p>
                            <p class="card-text">{{pacientes.tutor}}</p>
                            <p class="card-text">{{pacientes.direccion}}</p>
                            <p class="card-text">{{pacientes.enfermedades}}</p>
                    </div>
            {% endfor %}
        </div>
    </div>
        
</body>
</html>

M5_SitioMedico-01_JuanArancibia/app_forms/templates/app_forms/eliminar_pacientes.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'app1/css/estilos.css' %}">
</head>

<body>
    <!--Barra Navegacion-->
    <nav class="navbar navbar-expand-lg navbar navbar-dark bg-primary">
        <a class="navbar-brand" href="{% url 'app1:inicio' %}">InterSalud</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
            aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </nav>
    <!--Se bajan los iconos de navegacón-->
    <nav class="navbar navbar-expand-lg navbar navbar-dark bg-primary"> 

        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" >Administración </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app1:login' %}">Iniciar Sesion</a>
                </li>
                
                <!--Se agregan nuevas páginas a la barra de navegación-->
                
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app_forms:crear_pacientes' %}">Crear paciente</a>
                </li>
               
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app_forms:pacientes_creados' %}">Lista Pacientes</a>
                </li> 
                <!--En la lista_pacientes esta la opcion de de eliminarar paciente para eliminar-->
                                           
 
            </ul>

        </div>
    </nav>
<!--Fin Barra Navegación-->
        <!--Pregunta si el paciente se elimina o no, seleccionado en lista_cliente.html-->
    <div class = "jumbotron">
        <div class = "center-text">
            <form action="{% url 'app_forms:eliminar_pacientes' rut=rut %}" method="POST">
                {% csrf_token %}
                Se va a Eliminar Paciente con RUT N°  = {{rut}}.
                ¿Desea confirmar la acción?
                <input type="submit" value="Sí">
            </form>  
        </div>
    </div>

</body>
</html>

M5_SitioMedico-01_JuanArancibia/app_forms/templates/app_forms/lista_pacientes.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'app1/css/estilos.css' %}">
</head>

<body>
    <!--Barra Navegacion-->
    <nav class="navbar navbar-expand-lg navbar navbar-dark bg-primary">
        <a class="navbar-brand" href="{% url 'app1:inicio' %}">InterSalud</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
            aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </nav>
    <!--Se bajan los iconos de navegacón-->
    <nav class="navbar navbar-expand-lg navbar navbar-dark bg-primary"> 

        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'app1:administracion' %}">Administración </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app1:login' %}">Iniciar Sesion</a>
                </li>
                
                <!--Se agregan nuevas páginas a la barra de navegación-->
                
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app_forms:crear_pacientes' %}">Crear paciente</a>
                </li>
               
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app_forms:pacientes_creados' %}">Lista Pacientes</a>
                </li> 
                <!--En la lista_pacientes esta la opcion de de eliminarar paciente para eliminar-->
                
            </ul>

        </div>
    </nav>
<!--Fin Barra Navegación-->

<!--Selección de Pacientes a eliminar-->
        <h2>Seleccionar Paciente a Eliminar</h2>
        
        <div class="row">
                {% for paciente in lista_pacientes %}
                    <a href="{% url 'app_forms:eliminar_pacientes' rut=paciente.rut %}" 
                       class="card-title">{{paciente.rut}},
                        {{paciente.nombre}},
                        {{paciente.apellido}},
                        {{paciente.email}},
                        {{paciente.tutor}},
                        {{paciente.direccion}},
                        {{paciente.enfermedades}},  
                    
                {% endfor %}
        </div>
 <!--Fin Selección de Pacientes a eliminar-->
</body>
</html>

M5_SitioMedico-01_JuanArancibia/app_forms/templates/app_forms/pacientes_creados.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'app1/css/estilos.css' %}">
</head>

<body>
    <!--Barra Navegacion-->
    <nav class="navbar navbar-expand-lg navbar navbar-dark bg-primary">
        <a class="navbar-brand" href="{% url 'app1:inicio' %}">InterSalud</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
            aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link">Administración </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app1:login' %}">Iniciar Sesion</a>
                </li>
                
                <!--Se agregan nuevas páginas a la barra de navegación-->
                
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app_forms:crear_pacientes' %}">Crear paciente</a>
                </li>
               
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app_forms:pacientes_creados' %}">Lista Pacientes</a>
                </li> 
                <!--En la lista_pacientes esta la opcion de de eliminarar paciente para eliminar-->
                                            
 
            </ul>

        </div>
    </nav>
<!--Fin Barra Navegación-->

<!--Se listan los pacientes vigentes-->
<div class="jumbotron">
    <h2> Listado de Pacientes Creados</h2>
        <table class="table table-bordered">
            <thead>
                <tr>
                <th scope="col">Rut</th>
                <th scope="col">Nombre</th>
                <th scope="col">Apellidos</th>
                <th scope="col">Email</th>
                <th scope="col">Tutor</th>
                <th scope="col">Direccion</th>
                <th scope="col">Enfermedades</th>
                <th scope="col">Borrar</th>
                </tr>
            </thead>

            <tbody>
                {% for paciente in lista_pacientes %}
                <tr>
                    <th scope="row">{{ paciente.rut }}</th>
                    <td>{{ paciente.nombre }}</td>
                    <td>{{ paciente.apellido }}</td>
                    <td>{{ paciente.email }}</td>
                    <td>{{ paciente.tutor }}</td>
                    <td>{{ paciente.direccion }}</td>
                    <td>{{ paciente.enfermedades }}</td>
                    <td><a href="{% url 'app_forms:eliminar_pacientes' rut=paciente.rut %}" 
                       class="card-title">Borrar</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
</div>


</body>
</html>