M5_SitioMedico-01_JuanArancibia/M5_SitioMedico/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
    path('', include('app_forms.urls')),
    path('', include ('app2.urls')),
]

M5_SitioMedico-01_JuanArancibia/app1/urls.py
from django.urls import path
from . import views


app_name='app1'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('registro/', views.registro, name='registro'),
    path('login/', views.login, name='login'),
    path('fichaPaciente/', views.fichaPaciente, name='fichaPaciente'),
    
    path('calendario/', views.calendarioHoras, name='calendario'),
    path('administracion/', views.administracion, name='administracion'),
    
]

M5_SitioMedico-01_JuanArancibia/app_forms/urls.py
from django.urls import path
from . import views


app_name='app_forms'

urlpatterns = [
    path('crear_pacientes/', views.crear_pacientes, name='crear_pacientes'),
    path('lista_pacientes/', views.lista_pacientes, name='lista_pacientes'),
    path('<rut>/eliminar_pacientes', views.eliminar_pacientes, name='eliminar_pacientes'),
    path('pacientes_creados/', views.pacientes_creados, name='pacientes_creados'),
    path('ingresar_examenes/', views.ingresar_examenes, name='ingresar_examenes'),
]

M5_SitioMedico-01_JuanArancibia/app1/models.py
from django.db import models

# Create your models here.

M5_SitioMedico-01_JuanArancibia/app1/forms.py
import datetime

from django import forms
from django.core import validators
from django.core.exceptions import ValidationError


class FormularioBusqueda(forms.Form):
    Rut = forms.CharField(
            validators = [
                validators.MinLengthValidator( 9, 
						    "El RUN no puede tener menos de 9 caracteres"),
                        validators.MaxLengthValidator( 10, 
						    "El RUN no puede tener mas de 10 caracteres") ]) 
    contra = forms.CharField()
             

M5_SitioMedico-01_JuanArancibia/app1/views.py
from django.shortcuts import render, redirect
from django.template import loader, context
from django.http import HttpResponse
from django.http import HttpResponsePermanentRedirect
from .forms import FormularioBusqueda


# Create your views here.

def inicio(request):
    return render(request, 'app1/index.html')

def registro(request):
    return render(request, 'app1/register.html')


def fichaPaciente(request):
    return render(request, 'app1/fichapaciente.html')


def calendarioHoras(request):
    return render(request, 'app1/calendarioHoras.html')

def administracion(request):
    return render(request, 'app1/administracion.html')

def login(request):
    formulario = FormularioBusqueda()
    if request.method == "GET":
        formulario = FormularioBusqueda()
        context = {'formulario': formulario, 'invalid': False}
        return render(request, 'app1/login.html', context)

    elif request.method == "POST":
        formulario_devuelto = FormularioBusqueda(request.POST)

        if formulario_devuelto.is_valid() == True:
            data = formulario_devuelto.cleaned_data
            
            if data['Rut'] == '19220125-k' and data['contra'] == '12345':
                return redirect('app2:fichaMedica')
            else:
                return render(request, 'app1/login.html', context)

        
    return render(request, 'app1/login.html')

M5_SitioMedico-01_JuanArancibia/app1/templates/app1/administracion.html
{% extends "base.html" %}

{% load static %}

{% block contenidos %}


<body>

  <div class="jumbotron">
    <div class="row justify-content-between">
      <div class="col-4">
        <h1 class="display-4">Ficha Medica Empleado </h1>
      </div>
      <img src="{% static 'app1/img/hospital.jpg'%}" alt="Girl in a jacket" width="200" height="200">
      <img src="{% static 'app1/img/efermera.jpg'%}" alt="Girl in a jacket" width="200" height="200">
      <div class="col-4">
        <!-- weather widget start --><a target="_blank" href="https://hotelmix.es/weather/santiago-2114"><img
            src="https://w.bookcdn.com/weather/picture/1_2114_1_4_137AE9_160_ffffff_333333_08488D_1_ffffff_333333_0_6.png?scode=124&domid=582&anc_id=60694"
            alt="booked.net" /></a><!-- weather widget end -->
      </div>
    </div>
    <p class="lead"> Valida datos del empleado</p>
    <script>
      var f = new Date();
      document.write(f.getDate() + "/" + (f.getMonth() + 1) + "/" + f.getFullYear());
    </script>
    <div class="text-center">
      <hr class="my-4">
      <p>Cargo</p>
      <input type="Cargo">
      <p>Nombres</p>
      <input type="Nombres">
      <p>Apellidos</p>
      <input type="Apellidos">

    </div>
    <div class="text-center">
      <a class="btn btn-primary btn-lg" href="{% url 'app1:inicio' %}" role="button">Validar</a>
    </div>


  </div>

</body>

{% endblock %}

M5_SitioMedico-01_JuanArancibia/app1/templates/app1/calendarioHoras.html
{% extends "base.html" %}

{% load static %}

{% block contenidos %}

</head>
<!-- Barra -->
<body>
    <nav class="navbar navbar-expand-lg navbar navbar-dark bg-primary">
        <a class=" navbar-brand" href="#">InterSalud</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
            aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Calendario<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="./fichamedica.html">Ficha medica</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="./index.html">Cerrar Sesión </a>
                </li>
            </ul>
            <span class="navbar-text">
                text
            </span>
        </div>
    </nav>
    <img src="img/logo.png" alt="">
    </head>

    <body>

       

        <!-- Encabezado calendario-->
        <h1 class="fondo-destacado">Calendario de Atenciones</h1>
        <p>Haga click en el día que le interesa, para ver la Planificación Diaria:</p>

        <!-- Bloque imagen Calendario -->
        <div class="month">
            <ul>
                <li class="prev">&#10094;</li>
                <li class="next">&#10095;</li>
                <li>
                    Diciembre<br>
                    <span style="font-size:18px">2020</span>
                </li>
            </ul>
        </div>

        <ul class="weekdays">
            <li>Lunes</li>
            <li>Martes</li>
            <li>Miércoles</li>
            <li>Jueves</li>
            <li>Viernes</li>
            <li>Sábado</li>
            <li>Domingo</li>
        </ul>

        <ul class="days">
            <li></li>
            <li>1</li>
            <li>2</li>
            <li>3</li>
            <li>4</li>
            <li>5</li>
            <li>6</li>
            <li>7</li>
            <li>8</li>
            <li>9</li>
            <li><span class="active">10</span></li>
            <li>11</li>
            <li>12</li>
            <li>13</li>
            <li>14</li>
            <li>15</li>
            <li><span class="active">16</span></li>
            <li>17</li>
            <li>18</li>
            <li>19</li>
            <li>20</li>
            <li>21</li>
            <li>22</li>
            <li>23</li>
            <li>24</li>
            <li>25</li>
            <li>26</li>
            <li>27</li>
            <li>28</li>
            <li>29</li>
            <li>30</li>
            <li>31</li>
        </ul>

        <!-- js "Imprimir página" -->
        <input type="button" value="Imprime esta página" onclick="window.print()">
        <br>
        <br>





    </body>
{% endblock %}

M5_SitioMedico-01_JuanArancibia/app1/templates/app1/fichamedica.html
{% extends "base.html" %}

{% load static %}

{% block contenidos %}

<body>
  <div class="jumbotron">
    <div class="col xl">
      <div class="jumbotron">

        <h1 class="display-4">Ficha Medica Paciente </h1>
        <p class="lead"> Valida el rut del paciente para visualizar informacion Medica </p>
        <hr class="my-4">
        <p>Ingrese su RUT</p>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">InterSalud</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">

              </li>
              <li class="nav-item">

              </li>
              <li class="nav-item dropdown">

                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Something else here</a>
                </div>
              </li>
              <li class="nav-item"></li>

              </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="search" placeholder="RUT" aria-label="Search">

            </form>
            <!DOCTYPE html>
            <html>

            <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width">
              <title>JS Bin</title>
            </head>

            <a class="btn btn-primary btn-lg" href="{% url 'app1:fichaPaciente' %}" role="button">Ficha paciente</a>
            <div class="margen">
              <a class="btn btn-primary btn-lg" href="{% url 'app1:calendarioHoras' %}" role="button">Calendario
                paciente</a>
            </div>

          </div>
        </nav>
      </div>
    </div>
  </div>
</body>

{% endblock %}

M5_SitioMedico-01_JuanArancibia/app1/templates/app1/fichapaciente.html
{% extends "base.html" %}

{% load static %}

{% block contenidos %}

<body>
  <div class="jumbotron">
    <div class="col sm">
      <div class="jumbotron">
        <h1 class="display-4">Ficha Medica</h1>
        <p class="lead">Uso exclisivo del Paciente </p>
        <hr class="my-4">
      </div>
    </div>
  </div>
  </div>

  <!-- Pdf de la ficha medica -->
  <iframe src="{% static 'app1/ficha_medica_de_ejemplo.pdf'%}" width="100%" height="680px"></iframe>

</body>

{% endblock %}

M5_SitioMedico-01_JuanArancibia/app1/templates/app1/index.html
{% extends "base.html" %}

{% load static %}

{% block contenidos %}

<body>
  <!-- Bienvenidos-->
  <div class="jumbotron">
    <h1 class="display-4">¡Bienvenidos a InterSalud!</h1>
    <p class="lead">InterSalud disponibiliza la informacion de sus usuarios al instante. Registrate junto con tu
      información medica, o inicia sesion si ya estas registrado</p>
    <hr class="my-4">
    <p>Selecciona una opción</p>
    <p class="lead">
      <a class="btn btn-primary btn-lg" href="{% url 'app_forms:crear_pacientes' %}" role="button">Crear ficha paciente</a>
      <a class="btn btn-primary btn-lg" href="{% url 'app1:login' %}" role="button">Inicio de sesión</a>
    </p>
  </div>

  <!-- Sección Noticias-->
  <div class="container">
    <div class="row">

      
      <div class="col-sm">
        <div class="card" style="width: 18rem;">
          <img class="card-img-top" src="{% static 'app1/img/salud1.jpg'%}" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title">Dia internacional del donante</h5>
            <p class="card-text">El 9 de noviembre es el dia internacional del donante voluntario, enterate por que es
              importante donar</p>
            <a href="https://www.eltribuno.com/jujuy/nota/2020-11-9-12-53-0-dia-nacional-del-donante-voluntario-de-sangre"
              class="btn btn-primary">ir a la noticia</a>
          </div>
        </div>
      </div>

      <div class="col-sm">
        <div class="card" style="width: 18rem;">

          <img class="card-img-top" src="{% static 'app1/img/salud3.jpg'%}" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title">Una nueva plataforma para la salud</h5>
            <p class="card-text">Plataforma web acerca la salud digital a pacientes crónicos y personas en riesgo social
            </p>
            <a href="https://www.latercera.com/que-pasa/noticia/plataforma-web-acerca-la-salud-digital-a-pacientes-cronicos-y-personas-en-riesgo-social/CP7VXPWJGFDFDM35AKTK47JWSQ/"
              class="btn btn-primary">ir a la noticia</a>
          </div>
        </div>
      </div>

      <div class="col-sm">
        <div class="card" style="width: 18rem;">

          <img class="card-img-top" src="{% static 'app1/img/virus.jpg'%}" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title">Nuevas definiciones en la RAE</h5>
            <p class="card-text">La Real academia española ha incluido nuevos conceptos relacionados con la pandemia que
              azota al mundo</p>
            <a href="https://www.diarioarea.com/2020/11/24/covid-coronavirus-o-desconfinamiento-ya-estan-en-la-rae/"
              class="btn btn-primary">ir a la noticia</a>
          </div>
        </div>
      </div>
    </div>
  </div>

  <script>
    window.onload = function () { alert('Bienvenido a esta pagina'); }
  </script>

</body>

{% endblock %}

M5_SitioMedico-01_JuanArancibia/app1/templates/app1/login.html
{% extends "base.html" %}

{% load static %}

{% block contenidos %}


<body>
  <div class="center-text">
    <div class="card text-center">
      <div class="card-header">
        Inicio de Sesión
      </div>
      <div class="card-body">
        <div class="center">
          <div class="text-center">
            <img src="{% static 'app1/img/avatar2.png'%}" alt="Avatar" class="avatar" width='150px' height='100px'>
            <h5 class="card-title">Bienvenido</h5>
            <div class="colum">
            <form action="" method="POST" novalidate>
              {% csrf_token %}
              
                <table>
                    {{formulario.as_table}}
                </table>
                <input class="btn btn-primary btn-lg" type="submit" value="Iniciar Sesión">
            </form>

            
          </div>
          </div>
          

        </div>

      </div>

      <div class="card-footer text-muted">
        InterSalud
      </div>
    </div>
  </div>

  <script>
    function inicioSesion() {
      alert("Has iniciado sesión correctamente");
    }
  </script>


</body>
{% endblock %}

M5_SitioMedico-01_JuanArancibia/app1/templates/app1/register.html
{% extends "base.html" %}

{% load static %}

{% block contenidos %}


<body>

  <div class="center-text">
    <div class="card" style="width: 18rem;">
      <div class="card-header">
        <h5>Registro de usuarios</h5>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Ingresar nombre
          <input type="text" name="nombredelacaja">
        </li>
        <li class="list-group-item">Ingresa apellido
          <input type="text" name="nombredelacaja">
        </li>
        <li class="list-group-item">Ingresar RUN
          <input type="text" name="nombredelacaja">
        </li>
        <li class="list-group-item">Ingrese mail
          <input type="text" name="nombredelacaja">
        </li>
        <a class="btn btn-primary btn-lg" onclick="registrado()" href="{% url 'app1:login' %}"
          role="button">Registrar</a>

      </ul>
    </div>
  </div>

  <script>
    function registrado() {
      alert("El usuario ha sido registrado satisfactoriamente");
    }
  </script>

</body>

{% endblock %}