M5_SitioMedico-01_JuanArancibia/M5_SitioMedico/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
    path('', include('app_forms.urls')),
    path('', include ('app2.urls')),
]

M5_SitioMedico-01_JuanArancibia/app1/urls.py
from django.urls import path
from . import views


app_name='app1'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('registro/', views.registro, name='registro'),
    path('login/', views.login, name='login'),
    path('fichaPaciente/', views.fichaPaciente, name='fichaPaciente'),
    
    path('calendario/', views.calendarioHoras, name='calendario'),
    path('administracion/', views.administracion, name='administracion'),
    
]

M5_SitioMedico-01_JuanArancibia/app2/urls.py
from django.urls import path
from . import views


app_name='app2'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('registro/', views.registro, name='registro'),
    
    path('fichaPaciente/', views.lista_pacientes, name='fichaPaciente'),
    path('fichaMedica/', views.fichaMedica, name='fichaMedica'),
    path('calendario/', views.calendarioHoras, name='calendario'),
    path('administracion/', views.administracion, name='administracion'),
]

M5_SitioMedico-01_JuanArancibia/app_forms/urls.py
from django.urls import path
from . import views


app_name='app_forms'

urlpatterns = [
    path('crear_pacientes/', views.crear_pacientes, name='crear_pacientes'),
    path('lista_pacientes/', views.lista_pacientes, name='lista_pacientes'),
    path('<rut>/eliminar_pacientes', views.eliminar_pacientes, name='eliminar_pacientes'),
    path('pacientes_creados/', views.pacientes_creados, name='pacientes_creados'),
    path('ingresar_examenes/', views.ingresar_examenes, name='ingresar_examenes'),
]

M5_SitioMedico-01_JuanArancibia/app2/models.py
from django.db import models

# Create your models here.

M5_SitioMedico-01_JuanArancibia/app2/forms.py
import datetime

from django import forms
from django.core import validators
from django.core.exceptions import ValidationError


class FormularioBusqueda(forms.Form):
    Rut = forms.CharField(
            validators = [
                validators.MinLengthValidator( 9, 
						    "El RUN no puede tener menos de 9 caracteres"),
                        validators.MaxLengthValidator( 10, 
						    "El RUN no puede tener mas de 10 caracteres") ]) 
             
    

M5_SitioMedico-01_JuanArancibia/app2/views.py
import json
import datetime
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.conf import settings
from .forms import FormularioBusqueda

# Create your views here.

def inicio(request):
    return render(request, 'app2/index.html')

def registro(request):
    return render(request, 'app2/register.html')



def calendarioHoras(request):
    return render(request, 'app2/calendarioHoras.html')

def administracion(request):
    return render(request, 'app2/administracion.html')


def fichaMedica(request):
    formulario = FormularioBusqueda()
    if request.method == "GET":
        formulario = FormularioBusqueda()
        context = {'formulario': formulario, 'invalid': False}
        return render(request, 'app2/fichamedica.html', context)

    elif request.method == "POST":
        formulario_devuelto = FormularioBusqueda(request.POST)
        usuario_data = False
        lista2=[]
        datos=[]

        #print(formulario_devuelto)
        if formulario_devuelto.is_valid() == True:
            formulario_rut = formulario_devuelto.cleaned_data
            #print(formulario_rut, '########################################')
            usuario_data = verificar_user(formulario_rut)

        if usuario_data != False:
            lista_examenes = contex_examenes_paciente()
            lista_examenes2 = []
            for i in range (0,len(lista_examenes['lista_examenes'])):
                lista2.append(lista_examenes['lista_examenes'][i]['rut'])

            #creamos una nueva lista de examenes solo con el rut solicitado
            rut = str(usuario_data['rut'])
            for i in range (0, len(lista2)):
                lista_examenes2.append(lista2[i].get(rut))
            print(len(lista_examenes2))
            #sacamos los elementos none ligados a otros rut
            for elemento in lista_examenes2:
                if elemento == None:
                    print("elemento none")
                else:
                    datos.append(elemento)
            examen_filtrado = {'colesterol':[],'triglicerido':[],'orina': [],'glucosa':[],'bilirrubina':[], 'fecha':[]}
            for elemento in datos:   
                examen_filtrado['colesterol'].append(elemento['colesterol'])
                examen_filtrado['triglicerido'].append(elemento['triglicerido'])
                examen_filtrado['orina'].append(elemento['orina'])
                examen_filtrado['glucosa'].append(elemento['glucosa'])
                examen_filtrado['bilirrubina'].append(elemento['bilirrubina'])
                examen_filtrado['fecha'].append(elemento['fecha'])
            print(examen_filtrado['fecha'])
            context = {'usuario': usuario_data, 'lista_examenes': lista_examenes2, 'resultados':examen_filtrado}
            return render(request, 'app2/fichapaciente.html', context)
        elif formulario_devuelto.is_valid() == False:
            formulario = FormularioBusqueda()
            context = {'formulario': formulario, 'invalid': True}
            return render(request, 'app2/fichamedica.html', context)
        else:
            formulario = FormularioBusqueda()
            context = {'formulario': formulario, 'invalid': True}
            return render(request, 'app2/fichamedica.html', context)
    else:
        formulario = FormularioBusqueda()
        context = {'formulario': formulario, 'invalid': True}
        return render(request, 'app2/fichamedica.html', context)


def verificar_user(run_usuario):
    lista_usuarios = context_lista_pacientes()
    for paciente in lista_usuarios['lista_pacientes']:
        if paciente.get('rut') == run_usuario.get('Rut'):           
            return paciente
        else:
            continue
    return False


def context_lista_pacientes():
    filename = "/app_forms/data/pacientes.json"
    with open(str(settings.BASE_DIR)+filename, 'r') as file:
        pacientes = json.load(file)
    context = {'lista_pacientes': pacientes['pacientes']}
    return context


def lista_pacientes(request):
    context = context_lista_pacientes()
    return render(request, 'app2/fichapaciente.html', context)


def contex_examenes_paciente():
    filename = "/app2/data/examenes.json"
    with open(str(settings.BASE_DIR)+filename, 'r') as file:
        examenes = json.load(file)
    context = {'lista_examenes' : examenes['examenes']}
    return context

M5_SitioMedico-01_JuanArancibia/app2/templates/app2/administracion.html
{% extends "base.html" %}

{% load static %}

{% block contenidos %}


<body>

  <div class="jumbotron">
    <div class="row justify-content-between">
      <div class="col-4">
        <h1 class="display-4">Ficha Medica Empleado </h1>
      </div>
      <img src="{% static 'app2/img/hospital.jpg'%}" alt="Girl in a jacket" width="200" height="200">
      <img src="{% static 'app2/img/efermera.jpg'%}" alt="Girl in a jacket" width="200" height="200">
      <div class="col-4">
        <!-- weather widget start --><a target="_blank" href="https://hotelmix.es/weather/santiago-2114"><img
            src="https://w.bookcdn.com/weather/picture/1_2114_1_4_137AE9_160_ffffff_333333_08488D_1_ffffff_333333_0_6.png?scode=124&domid=582&anc_id=60694"
            alt="booked.net" /></a><!-- weather widget end -->
      </div>
    </div>
    <p class="lead"> Valida datos del empleado</p>
    <script>
      var f = new Date();
      document.write(f.getDate() + "/" + (f.getMonth() + 1) + "/" + f.getFullYear());
    </script>
    <div class="text-center">
      <hr class="my-4">
      <p>Cargo</p>
      <input type="Cargo">
      <p>Nombres</p>
      <input type="Nombres">
      <p>Apellidos</p>
      <input type="Apellidos">

    </div>
    <div class="text-center">
      <a class="btn btn-primary btn-lg" href="{% url 'app2:inicio' %}" role="button">Validar</a>
    </div>


  </div>

</body>

{% endblock %}

M5_SitioMedico-01_JuanArancibia/app2/templates/app2/calendarioHoras.html
{% extends "base.html" %}

{% load static %}

{% block contenidos %}

</head>

<body>

    <img src="{% static 'app2/logo.png'%}" alt="">
    </head>

    <body>
        <!-- Encabezado calendario-->
        <h1 class="fondo-destacado">Calendario de Atenciones</h1>
        <p>Haga click en el día que le interesa, para ver la Planificación Diaria:</p>

        <!-- Bloque imagen Calendario -->
        <div class="month">
            <ul>
                <li class="prev">&#10094;</li>
                <li class="next">&#10095;</li>
                <li>
                    Febrero<br>
                    <span style="font-size:18px">2021</span>
                </li>
            </ul>
        </div>

        <ul class="weekdays">
            <li>Lunes</li>
            <li>Martes</li>
            <li>Miércoles</li>
            <li>Jueves</li>
            <li>Viernes</li>
            <li>Sábado</li>
            <li>Domingo</li>
        </ul>

        <ul class="days">
            <li></li>
            <li>1</li>
            <li>2</li>
            <li>3</li>
            <li>4</li>
            <li>5</li>
            <li>6</li>
            <li>7</li>
            <li>8</li>
            <li>9</li>
            <li><span class="active">10</span></li>
            <li>11</li>
            <li>12</li>
            <li>13</li>
            <li>14</li>
            <li>15</li>
            <li><span class="active">16</span></li>
            <li>17</li>
            <li>18</li>
            <li>19</li>
            <li>20</li>
            <li>21</li>
            <li>22</li>
            <li>23</li>
            <li>24</li>
            <li>25</li>
            <li>26</li>
            <li>27</li>
            <li>28</li>

        </ul>

        <!-- js "Imprimir página" -->
        <input type="button" value="Imprime esta página" onclick="window.print()">
        <br>
        <br>

    </body>
    {% endblock %}

M5_SitioMedico-01_JuanArancibia/app2/templates/app2/fichamedica.html
{% extends "base.html" %}

{% load static %}

{% block contenidos %}

<body>
  <div class="jumbotron">
    <div class="col xl">
      <div class="jumbotron">

        <h1 class="display-4">Ficha Medica </h1>
        <p class="lead"> Valida el rut del paciente para visualizar informacion Medica </p>
        <hr class="my-4">
        <p>Ingrese su RUT</p>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="margen">
            <h2>Intersalud</h2>
          </div>
          
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">

              </li>
              <li class="nav-item">

              </li>
              <li class="nav-item dropdown">

                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Something else here</a>
                </div>
              </li>
              <li class="nav-item"></li>

              </li>
            </ul>
            <div class = 'row'>
              <div class='margen'>
              <form action="" method="POST" novalidate>
                  {% csrf_token %}
                  <div class="row">
                  
                    <table>
                        {{formulario.as_table}}
                    </table>
                    <input class="btn btn-primary btn-lg" type="submit" value="Buscar">
                
                  </div>
              </form>
            </div>
            <div class="margen">
            <p class="lead">
              <a class="btn btn-primary btn-lg" href="{% url 'app_forms:ingresar_examenes' %}" role="button">Ingresar Examen</a>
            </p>
            </div>
            </div>
            </div>

            {% if invalid == True %}
          
            <script>
              window.onload = function () { alert('El usuario no fue encontrado'); }
            </script>
            {% endif %}



          </div>
        </nav>
      </div>
    </div>
  </div>
</body>

{% endblock %}

M5_SitioMedico-01_JuanArancibia/app2/templates/app2/fichapaciente.html
{% extends "base.html" %}

{% load static %}

{% block contenidos %}

<body>
  <div class="jumbotron">
    <div class="col sm"> <div>
      <div>



  <div class="jumbotron">
      <h1 class="display-4">Ficha Paciente </h1>
      <p class="lead">Perfil de Usuario </p>
      <hr class="my-4">
      <p>
          <div>
            
          </div>
  <!-- Datos -->


  
 
<div class = 'row'>
  <ul>
    <li><strong>Nombre:</strong> {{ usuario.nombre }}</li>
    <li><strong>Apellido:</strong> {{ usuario.apellido }}</li>
    <li><strong>Dirección:</strong> {{ usuario.direccion }}</li>
    <li><strong>E-mail:</strong> {{ usuario.email }}</li>
    <li><strong>Tutor de contacto:</strong> {{ usuario.tutor }}</li>
    <li><strong>Enfermedades:</strong> {{ usuario.enfermedades }}</li>
  </ul>

 <!-- Inicio de grafico -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.js"></script>
        <style>
            .chart {
                width:50%;
                margin : 0 auto;
            }
        </style>

<div class="chart">
    <canvas id="barra"></canvas>
</div>  

</body>
<script>
var ctx= document.getElementById("barra");
var barra= new Chart(ctx,{



    type:"line",
    data:{
        labels:{{resultados.fecha|safe}},
        datasets:[{
                label:'colesterol',
                data:{{resultados.colesterol }},
                borderColor:['rgba(220, 20, 220, 1)'          
                ], 
                fill:false
        },
        {
                label:'trigliceridos',
                data:{{resultados.triglicerido }},
                borderColor:['rgba(150, 150, 10, 1)'                  
                ], 
                fill:false
        },
        {
                label:'orina',
                data:{{resultados.orina }},
                borderColor:['rgba(0, 80, 80, 1)'                
                ], 
                fill:false
        },
        {
                label:'glucosa',
                data:{{resultados.glucosa }},
                borderColor:['rgba(40, 0, 0, 1)'                   
                ], 
                fill:false
        },{
                label:'bilirrubina',
                data:{{resultados.bilirrubina }},
                borderColor:['rgba(180, 50, 10, 1)'                   
                ], 
                fill:false
        }]
    },
    options:{
        scales:{
            yAxes:[{
                    ticks:{
                        beginAtZero:true
                    }
            }]
        }
    }
});
</script>

<!-- fin de grafico-->>



</div>

<!-- Tabla-->
  <table class="table table-bordered">
    
    <colgroup>
    
      <colgroup span="2" style="background: rgba(128, 255, 0, 0.3); border: 1px solid rgba(100, 200, 0, 0.3);"></colgroup>
      <colgroup span="2" style="background: rgba(255, 128, 0, 0.3); border: 1px solid rgba(200, 100, 0, 0.3);"></colgroup>
      <colgroup span="2" style="background: rgba(110, 25, 0, 0.3); border: 1px solid rgba(100, 200, 0, 0.3);"></colgroup>
      <colgroup span="2" style="background: rgba(155, 55, 0, 0.3); border: 1px solid rgba(200, 100, 0, 0.3);"></colgroup>
    <thead>
      <tr>
        <th scope="col">Fecha</th>
        <th scope="col">Colesterol</th>
        <th scope="col">Triglicéridos</th>
        <th scope="col">Orina</th>
        <th scope="col">Glucosa</th>
        <th scope="col">Bilirrubina</th>
      </tr>
    </thead>
    <tbody>
      

      {% for examen in lista_examenes %}
     
      <tr>
        <th scope="row">{{ examen.fecha }}</th>
        <td>{{ examen.colesterol }}</td>
        <td>{{ examen.triglicerido }}</td>
        <td>{{ examen.orina }}</td>
        <td>{{ examen.glucosa }}</td>
        <td>{{ examen.bilirrubina }}</td>
      </tr>
      {% endfor %}
     
      <br>
      <br>
    </tbody>
  </table>

</body>

{% endblock %}

M5_SitioMedico-01_JuanArancibia/app2/templates/app2/index.html
{% extends "base.html" %}

{% load static %}

{% block contenidos %}

<body>
  <!-- Bienvenidos-->
  <div class="jumbotron">
    <h1 class="display-4">¡Bienvenidos a InterSalud!</h1>
    <p class="lead">InterSalud disponibiliza la informacion de sus usuarios al instante. Registrate junto con tu
      información medica, o inicia sesion si ya estas registrado</p>
    <hr class="my-4">
    <p>Selecciona una opción</p>
    <p class="lead">
      <a class="btn btn-primary btn-lg" href="{% url 'app2:registro' %}" role="button">Registro</a>
      <a class="btn btn-primary btn-lg" href="{% url 'app2:login' %}" role="button">Inicio de sesión</a>
    </p>
  </div>

  <!-- Sección Noticias-->
  <div class="container">
    <div class="row">

      <img class="card-img-top" src="{% static 'app2/img/virus.jpg'%}" alt="Card image cap">
      <div class="col-sm">
        <div class="card" style="width: 18rem;">
          <img class="card-img-top" src="{% static 'app2/img/salud1.jpg'%}" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title">Dia internacional del donante</h5>
            <p class="card-text">El 9 de noviembre es el dia internacional del donante voluntario, enterate por que es
              importante donar</p>
            <a href="https://www.eltribuno.com/jujuy/nota/2020-11-9-12-53-0-dia-nacional-del-donante-voluntario-de-sangre"
              class="btn btn-primary">ir a la noticia</a>
          </div>
        </div>
      </div>

      <div class="col-sm">
        <div class="card" style="width: 18rem;">

          <img class="card-img-top" src="{% static 'app2/img/salud3.jpg'%}" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title">Una nueva plataforma para la salud</h5>
            <p class="card-text">Plataforma web acerca la salud digital a pacientes crónicos y personas en riesgo social
            </p>
            <a href="https://www.latercera.com/que-pasa/noticia/plataforma-web-acerca-la-salud-digital-a-pacientes-cronicos-y-personas-en-riesgo-social/CP7VXPWJGFDFDM35AKTK47JWSQ/"
              class="btn btn-primary">ir a la noticia</a>
          </div>
        </div>
      </div>

      <div class="col-sm">
        <div class="card" style="width: 18rem;">

          <img class="card-img-top" src="{% static 'app2/img/virus.jpg'%}" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title">Nuevas definiciones en la RAE</h5>
            <p class="card-text">La Real academia española ha incluido nuevos conceptos relacionados con la pandemia que
              azota al mundo</p>
            <a href="https://www.diarioarea.com/2020/11/24/covid-coronavirus-o-desconfinamiento-ya-estan-en-la-rae/"
              class="btn btn-primary">ir a la noticia</a>
          </div>
        </div>
      </div>
    </div>
  </div>

  <script>
    window.onload = function () { alert('Bienvenido a esta pagina'); }
  </script>

</body>

{% endblock %}

M5_SitioMedico-01_JuanArancibia/app2/templates/app2/login.html
{% extends "base.html" %}

{% load static %}

{% block contenidos %}


<body>
  <div class="center-text">
    <div class="card text-center">
      <div class="card-header">
        Inicio de Sesión
      </div>
      <div class="card-body">
        <div class="center">
          <div class="text-center">
            <img src="{% static 'app2/img/avatar2.png'%}" alt="Avatar" class="avatar" width='150px' height='100px'>
            <h5 class="card-title">Bienvenido000000</h5>
            <p class="card-text">Ingresa tu correo</p>
            <input type="text" name="nombredelacaja">
            <p class="card-text">Ingresa tu contraseña</p>
            <input type="text" name="nombredelacaja">

          </div>

          <form action="" method="POST" novalidate>
            {% csrf_token %}
            <div class="row">
            
              <table>
                  {{formulario.as_table}}
              </table>
              <input class="btn btn-primary btn-lg" type="submit" value="Buscar">
          
            </div>
          </form>

          <div class="margen">
            <a onclick='inicioSesion()' href="{% url 'app2:fichaMedica' %}" class="btn btn-primary">Iniciar Sesión</a>
          </div>

        </div>

      </div>

      <div class="card-footer text-muted">
        InterSalud
      </div>
    </div>
  </div>

  <script>
    function inicioSesion() {
      alert("Has iniciado sesión correctamente");
    }
  </script>


</body>
{% endblock %}

M5_SitioMedico-01_JuanArancibia/app2/templates/app2/register.html
{% extends "base.html" %}

{% load static %}

{% block contenidos %}


<body>

  <div class="center-text">
    <div class="card" style="width: 18rem;">
      <div class="card-header">
        <h5>Registro de usuarios</h5>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Ingresar nombre
          <input type="text" name="nombredelacaja">
        </li>
        <li class="list-group-item">Ingresa apellido
          <input type="text" name="nombredelacaja">
        </li>
        <li class="list-group-item">Ingresar RUN
          <input type="text" name="nombredelacaja">
        </li>
        <li class="list-group-item">Ingrese mail
          <input type="text" name="nombredelacaja">
        </li>
        <a class="btn btn-primary btn-lg" onclick="registrado()" href="{% url 'app2:login' %}"
          role="button">Registrar</a>

      </ul>
    </div>
  </div>

  <script>
    function registrado() {
      alert("El usuario ha sido registrado satisfactoriamente");
    }
  </script>

</body>

{% endblock %}